// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package pingexport

import (
	"github.com/go-micro-saas/service-kit/server"
	"github.com/go-micro-saas/service-kit/setup"
	"github.com/go-micro-saas/service-kit/testdata/ping-service/api"
)

// Injectors from wire.go:

func initServices(launcherManager setuputil.LauncherManager) (*Services, error) {
	v := api.GetAuthWhiteList()
	server, err := serverutil.NewHTTPServer(launcherManager, v)
	if err != nil {
		return nil, err
	}
	grpcServer, err := serverutil.NewGRPCServer(launcherManager, v)
	if err != nil {
		return nil, err
	}
	services, err := NewServices(server, grpcServer)
	if err != nil {
		return nil, err
	}
	return services, nil
}
